<?php

namespace Kr\OAuthClientBundle\Repository;

/**
 * AuthorizationCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorizationCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
