<?php

namespace Kr\OAuthClientBundle\Repository;

/**
 * BearerTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BearerTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
