services:

    kr.oauth_client.http_client:
        class: GuzzleHttp\Client

    kr.oauth:
        class: Kr\OAuthClientBundle\DependencyInjection\Factory\OAuthFactory
        arguments:
            - "@kr.oauth_client.http_client"
            - "@kr.oauth_client.authentication_manager"
            - "@kr.oauth_client.repository.client"